apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: 852405188872.dkr.ecr.us-west-2.amazonaws.com/myimages:c746a377825b19650ba1d088f50478ba43be9f2f
        ports:
        - containerPort: 80

        