apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: 852405188872.dkr.ecr.us-west-2.amazonaws.com/myimages:867eefcfff0371a5f8de0034cbddbb225ebd2409
        ports:
        - containerPort: 80

        