apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: 852405188872.dkr.ecr.us-west-2.amazonaws.com/myimages:0fdfe10a166b12d2f1c206320cf36f75da9fd8ca
        ports:
        - containerPort: 80

        